<SQLBuilder_Common>

DECLARE @SQL_Work VARCHAR(MAX)
DECLARE @FileGroup VARCHAR(50) = '' --QUOTENAME(@DestSchema + 'FG')
DECLARE @CreateTable_Work VARCHAR(200) = 'CREATE TABLE [work].' + QUOTENAME(@SourceSchema + '_' + @SourceTable) + ' ('
DECLARE @PK VARCHAR(200), @EP VARCHAR(MAX)

SET @PK = 'CONSTRAINT [PK_' + @SourceSchema + '_' + @SourceTable + '] PRIMARY KEY CLUSTERED ('
SELECT @iCount = MAX(Id) FROM @Cols AS c WHERE c.PKOrdinal = 1
WHILE (SELECT MAX(Id) FROM @Cols AS c WHERE c.PKOrdinal > 0) >= @iCount	
BEGIN
	SELECT @PK = @PK + IIF((SELECT MAX(Id) FROM @Cols AS c WHERE c.PKOrdinal = 1) < @iCount, ', ', '') + QUOTENAME(c.ColName) + ' ASC'
	FROM @Cols AS c
	WHERE c.Id = @iCount
	SET @iCount = @iCount + 1
END	


-- Work Table
SET @SQL_Work = '-- Generated by CreateDWScripts.tt - SQLBuilder_Tables.sql'	-- No datetime because it will only overwrite if different and date guarantees this
SET @SQL_Work = @SQL_Work + @CR + @CreateTable_Work

SET @iCount = 1
WHILE (SELECT MAX(Id) FROM @Cols AS c) >= @iCount	
BEGIN
	SELECT @SQL_Work = @SQL_Work + @CR + SPACE(5) + QUOTENAME(c.ColName) + SPACE(@MaxColLen + 5 - LEN(QUOTENAME(c.ColName))) + c.DataType + SPACE(18 - LEN(c.DataType)) + IIF(c.Nullable = 'NO', 'NOT NULL', 'NULL') 
		+ CASE WHEN c.DefaultConstraint IS NOT NULL THEN ' CONSTRAINT [DF_' + @SourceSchema + '_' + @SourceTable + '_' + c.ColName + '] DEFAULT (' + c.DefaultConstraint + ')' ELSE '' END	
		+ IIF((SELECT MAX(Id) FROM @Cols AS c) > @iCount, ',', '')
	FROM @Cols AS c
	WHERE c.Id = @iCount
	
	SET @iCount = @iCount + 1
END	

--SET @SQL_Work = @SQL_Work + @CR + SPACE(5) + @PK + '),' -- No Primary keys on work table as it helps debugging PK violations

SET @SQL_Work = @SQL_Work + @CR + ') ' --ON [workFG]'

--IF ((SELECT COUNT(1) FROM @Cols WHERE TextImageFGRequired = 1) > 0)
--	SET @SQL_Work = @SQL_Work + ' TEXTIMAGE_ON [workFG]'

--SET @SQL_Work = @SQL_Work + ';'

SET @SQL_Work = @SQL_Work + @CR + 'GO' + @CR
 
SELECT @TargetSchema + '_' + @SourceTable + '.sql', 'work\Tables', @SQL_Work
--UNION ALL
--SELECT @SourceSchema + '_' + @SourceTable + '.sql', 'error\Tables', REPLACE(@SQL_Work, '[work].','[error].')

